apiVersion: batch/v1
kind: Job
metadata:
  name:  centos-job
spec:
  template:
    metadata:
      name:  centos-pod
    spec:
      containers:
      - name: centos-container
        image: centos:7
        command: ["bash"]
        args:
        - "-c"
        - "echo 'hi'; sleep 50; echo 'bye'"
      restartPolicy: Never