kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-rs
spec:
  selector:
    matchLabels:
      app: webui
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
        - name: nginx-containers
          image: nginx:1.14
          ports:
          - containerPort: 80
          
