---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer-container
        image: adminer
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: adminer-svc
spec:
  selector:
    app: adminer
  ports:
  - port: 8080
    targetPort: 8080
    