kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: main
        image: mongo
        args: 
        - sleep
        - 1d
        ports:
        - containerPort: 27017
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: tensorflow-gpu
            topologyKey: kubernetes.io/hostname